package com.amazon.videobroadcast;

import static com.amazon.videobroadcast.AWSResourceSetup.*;

import java.util.Date;
import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.S3Link;


@DynamoDBTable(tableName = "video-broadcast-mw2907")
public class Video {
	
	private String id;
    private String topic;
    private String type;
    private String fileName;
	private S3Link videoS3Link;
    private String createdBy;
    private Date creationTime;
	
    
    public Video(String topic, String type, String fileName, String createdBy,String s3linkKey) {
		super();
		this.topic = topic;
		this.type = type;
		this.fileName = fileName;
		this.createdBy = createdBy;
		this.creationTime=new Date();
		this.videoS3Link=DYNAMODB_MAPPER.createS3Link(S3_BUCKET_NAME, s3linkKey);
	}
    
    public void saveVideoToDynamoDB(){
    	DYNAMODB_MAPPER.save(this);
    }
    
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getTopic() {
		return topic;
	}
	public void setTopic(String topic) {
		this.topic = topic;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public S3Link getVideoS3Link() {
		return videoS3Link;
	}
	public void setVideoS3Link(S3Link videoS3Link) {
		this.videoS3Link = videoS3Link;
	}
	public String getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public Date getCreationTime() {
		return creationTime;
	}
	public void setCreationTime(Date creationTime) {
		this.creationTime = creationTime;
	}
	public String getFileName() {
			return fileName;
	}
	public void setFileName(String fileName) {
			this.fileName = fileName;
	}
	
	public static void main(String[] args) {
		 Video v=new Video("test","topic", "myTestVideo", "mengyuwu", "myTestVideo123");
		 v.saveVideoToDynamoDB();
		 
	}

}
